services:
  - type: web
    name: tormonitor
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
    startCommand: apache2-foreground